
package com.cloanto.webservices.currencyserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CurrencyServerSoap", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CurrencyServerSoap {


    /**
     * Loads a settings file. Access to this administrative operation may be restricted.
     * 
     * @param licenseKey
     * @param file
     */
    @WebMethod(operationName = "AdminLoad", action = "http://webservices.cloanto.com/currencyserver/AdminLoad")
    @RequestWrapper(localName = "AdminLoad", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.AdminLoad")
    @ResponseWrapper(localName = "AdminLoadResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.AdminLoadResponse")
    public void adminLoad(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "file", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String file);

    /**
     * Sends a message as specified in the notification options. Access to this administrative operation may be restricted.
     * 
     * @param licenseKey
     * @param text
     * @param type
     */
    @WebMethod(operationName = "AdminMessage", action = "http://webservices.cloanto.com/currencyserver/AdminMessage")
    @RequestWrapper(localName = "AdminMessage", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.AdminMessage")
    @ResponseWrapper(localName = "AdminMessageResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.AdminMessageResponse")
    public void adminMessage(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "text", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String text,
        @WebParam(name = "type", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        int type);

    /**
     * Saves a settings file. Access to this administrative operation may be restricted.
     * 
     * @param licenseKey
     * @param file
     */
    @WebMethod(operationName = "AdminSave", action = "http://webservices.cloanto.com/currencyserver/AdminSave")
    @RequestWrapper(localName = "AdminSave", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.AdminSave")
    @ResponseWrapper(localName = "AdminSaveResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.AdminSaveResponse")
    public void adminSave(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "file", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String file);

    /**
     * Establishes a connection to the data source(s) and updates the currency data. Access to this administrative operation may be restricted.
     * 
     * @param licenseKey
     */
    @WebMethod(operationName = "AdminUpdateNow", action = "http://webservices.cloanto.com/currencyserver/AdminUpdateNow")
    @RequestWrapper(localName = "AdminUpdateNow", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.AdminUpdateNow")
    @ResponseWrapper(localName = "AdminUpdateNowResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.AdminUpdateNowResponse")
    public void adminUpdateNow(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Converts a currency amount. The result is a number which can optionally be rounded. Leave the date and type parameters empty for forward compatibility.
     * 
     * @param date
     * @param licenseKey
     * @param amount
     * @param toCurrency
     * @param rounding
     * @param fromCurrency
     * @param type
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertToNum", action = "http://webservices.cloanto.com/currencyserver/ConvertToNum")
    @WebResult(name = "ConvertToNumResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "ConvertToNum", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.ConvertToNum")
    @ResponseWrapper(localName = "ConvertToNumResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.ConvertToNumResponse")
    public double convertToNum(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "fromCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String fromCurrency,
        @WebParam(name = "toCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String toCurrency,
        @WebParam(name = "amount", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        double amount,
        @WebParam(name = "rounding", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        boolean rounding,
        @WebParam(name = "date", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String date,
        @WebParam(name = "type", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String type);

    /**
     * Converts a currency amount. The result is a string which can optionally be rounded and formatted. Either fromCurrency or toCurrency (but not both) may contain a list of semicolon-separated active currencies. Leave the date and type parameters empty for forward compatibility.
     * 
     * @param date
     * @param licenseKey
     * @param amount
     * @param toCurrency
     * @param format
     * @param rounding
     * @param fromCurrency
     * @param type
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConvertToStr", action = "http://webservices.cloanto.com/currencyserver/ConvertToStr")
    @WebResult(name = "ConvertToStrResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "ConvertToStr", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.ConvertToStr")
    @ResponseWrapper(localName = "ConvertToStrResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.ConvertToStrResponse")
    public String convertToStr(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "fromCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String fromCurrency,
        @WebParam(name = "toCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String toCurrency,
        @WebParam(name = "amount", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        double amount,
        @WebParam(name = "rounding", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        boolean rounding,
        @WebParam(name = "format", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String format,
        @WebParam(name = "date", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String date,
        @WebParam(name = "type", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String type);

    /**
     * Returns a currency code (ISO 4217 Alpha-3) associated to the specified country (ISO 3166 Alpha-2).
     * 
     * @param activeOnly
     * @param licenseKey
     * @param country
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CountryToCurrency", action = "http://webservices.cloanto.com/currencyserver/CountryToCurrency")
    @WebResult(name = "CountryToCurrencyResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CountryToCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CountryToCurrency")
    @ResponseWrapper(localName = "CountryToCurrencyResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CountryToCurrencyResponse")
    public String countryToCurrency(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "country", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String country,
        @WebParam(name = "activeOnly", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        boolean activeOnly);

    /**
     * Returns a semicolon-separated list of active currencies.
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Currencies", action = "http://webservices.cloanto.com/currencyserver/Currencies")
    @WebResult(name = "CurrenciesResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "Currencies", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.Currencies")
    @ResponseWrapper(localName = "CurrenciesResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrenciesResponse")
    public String currencies(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the currency custom string based on the specified locale. The currency parameter may contain a list of semicolon-separated active currencies.
     * 
     * @param licenseKey
     * @param currency
     * @param locale
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurrencyCustom", action = "http://webservices.cloanto.com/currencyserver/CurrencyCustom")
    @WebResult(name = "CurrencyCustomResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyCustom", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyCustom")
    @ResponseWrapper(localName = "CurrencyCustomResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyCustomResponse")
    public String currencyCustom(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency,
        @WebParam(name = "locale", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String locale);

    /**
     * Returns a Boolean value indicating whether the currency is included in the list of active currencies.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CurrencyExists", action = "http://webservices.cloanto.com/currencyserver/CurrencyExists")
    @WebResult(name = "CurrencyExistsResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyExists", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyExists")
    @ResponseWrapper(localName = "CurrencyExistsResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyExistsResponse")
    public boolean currencyExists(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns the number of times this currency has been referenced by a COM object or by the Web service.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns long
     */
    @WebMethod(operationName = "CurrencyHits", action = "http://webservices.cloanto.com/currencyserver/CurrencyHits")
    @WebResult(name = "CurrencyHitsResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyHits", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyHits")
    @ResponseWrapper(localName = "CurrencyHitsResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyHitsResponse")
    public long currencyHits(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns the date and time of the last modification to the Rate property (local time). If the rate has never been set or changed an empty string is returned. The currency parameter may contain a list of semicolon-separated active currencies.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurrencyLastChangeTimeLocal", action = "http://webservices.cloanto.com/currencyserver/CurrencyLastChangeTimeLocal")
    @WebResult(name = "CurrencyLastChangeTimeLocalResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyLastChangeTimeLocal", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyLastChangeTimeLocal")
    @ResponseWrapper(localName = "CurrencyLastChangeTimeLocalResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyLastChangeTimeLocalResponse")
    public String currencyLastChangeTimeLocal(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns the date and time of the last modification to the Rate property (Universal Time). If the rate has never been set or changed an empty string is returned. The currency parameter may contain a list of semicolon-separated active currencies.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurrencyLastChangeTimeUT", action = "http://webservices.cloanto.com/currencyserver/CurrencyLastChangeTimeUT")
    @WebResult(name = "CurrencyLastChangeTimeUTResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyLastChangeTimeUT", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyLastChangeTimeUT")
    @ResponseWrapper(localName = "CurrencyLastChangeTimeUTResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyLastChangeTimeUTResponse")
    public String currencyLastChangeTimeUT(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns a Boolean value indicating whether the currency is legal tender.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CurrencyLegalTender", action = "http://webservices.cloanto.com/currencyserver/CurrencyLegalTender")
    @WebResult(name = "CurrencyLegalTenderResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyLegalTender", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyLegalTender")
    @ResponseWrapper(localName = "CurrencyLegalTenderResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyLegalTenderResponse")
    public boolean currencyLegalTender(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns the extended name of the currency based on the specified locale and title style. The currency parameter may contain a list of semicolon-separated active currencies.
     * 
     * @param licenseKey
     * @param currency
     * @param titleStyle
     * @param locale
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurrencyName", action = "http://webservices.cloanto.com/currencyserver/CurrencyName")
    @WebResult(name = "CurrencyNameResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyName", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyName")
    @ResponseWrapper(localName = "CurrencyNameResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyNameResponse")
    public String currencyName(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency,
        @WebParam(name = "locale", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String locale,
        @WebParam(name = "titleStyle", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        boolean titleStyle);

    /**
     * Returns a Boolean value indicating whether the currency is a physical currency.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CurrencyPhysical", action = "http://webservices.cloanto.com/currencyserver/CurrencyPhysical")
    @WebResult(name = "CurrencyPhysicalResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyPhysical", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyPhysical")
    @ResponseWrapper(localName = "CurrencyPhysicalResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyPhysicalResponse")
    public boolean currencyPhysical(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns the identifier of a regime or monetary union or an empty string. The currency parameter may contain a list of semicolon-separated active currencies.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurrencyRegime", action = "http://webservices.cloanto.com/currencyserver/CurrencyRegime")
    @WebResult(name = "CurrencyRegimeResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyRegime", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyRegime")
    @ResponseWrapper(localName = "CurrencyRegimeResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyRegimeResponse")
    public String currencyRegime(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns the seconds elapsed since the last modification to the currency's exchange rate.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns long
     */
    @WebMethod(operationName = "CurrencySecondsSinceLastChange", action = "http://webservices.cloanto.com/currencyserver/CurrencySecondsSinceLastChange")
    @WebResult(name = "CurrencySecondsSinceLastChangeResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencySecondsSinceLastChange", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencySecondsSinceLastChange")
    @ResponseWrapper(localName = "CurrencySecondsSinceLastChangeResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencySecondsSinceLastChangeResponse")
    public long currencySecondsSinceLastChange(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns the number of servers providing exchange rate data for the currency.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns long
     */
    @WebMethod(operationName = "CurrencyServers", action = "http://webservices.cloanto.com/currencyserver/CurrencyServers")
    @WebResult(name = "CurrencyServersResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyServers", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyServers")
    @ResponseWrapper(localName = "CurrencyServersResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyServersResponse")
    public long currencyServers(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns the smallest unit for the currency. Trailing zero characters are used to specify the preferred format for rounding. The currency parameter may contain a list of semicolon-separated active currencies.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurrencySmallestUnit", action = "http://webservices.cloanto.com/currencyserver/CurrencySmallestUnit")
    @WebResult(name = "CurrencySmallestUnitResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencySmallestUnit", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencySmallestUnit")
    @ResponseWrapper(localName = "CurrencySmallestUnitResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencySmallestUnitResponse")
    public String currencySmallestUnit(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns a Boolean value indicating whether the currency is a subunit of BaseUnit at a constant rate.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CurrencySubUnit", action = "http://webservices.cloanto.com/currencyserver/CurrencySubUnit")
    @WebResult(name = "CurrencySubUnitResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencySubUnit", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencySubUnit")
    @ResponseWrapper(localName = "CurrencySubUnitResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencySubUnitResponse")
    public boolean currencySubUnit(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns the currency symbol based on the specified locale. The currency parameter may contain a list of semicolon-separated active currencies.
     * 
     * @param licenseKey
     * @param currency
     * @param locale
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurrencySymbol", action = "http://webservices.cloanto.com/currencyserver/CurrencySymbol")
    @WebResult(name = "CurrencySymbolResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencySymbol", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencySymbol")
    @ResponseWrapper(localName = "CurrencySymbolResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencySymbolResponse")
    public String currencySymbol(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency,
        @WebParam(name = "locale", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String locale);

    /**
     * Returns a Boolean value indicating whether the currency has been referenced by a recent warning condition.
     * 
     * @param licenseKey
     * @param currency
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CurrencyWarning", action = "http://webservices.cloanto.com/currencyserver/CurrencyWarning")
    @WebResult(name = "CurrencyWarningResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrencyWarning", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyWarning")
    @ResponseWrapper(localName = "CurrencyWarningResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrencyWarningResponse")
    public boolean currencyWarning(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "currency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String currency);

    /**
     * Returns the current date and time (local time).
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurrentTimeLocal", action = "http://webservices.cloanto.com/currencyserver/CurrentTimeLocal")
    @WebResult(name = "CurrentTimeLocalResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrentTimeLocal", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrentTimeLocal")
    @ResponseWrapper(localName = "CurrentTimeLocalResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrentTimeLocalResponse")
    public String currentTimeLocal(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the current date and time (Universal Time).
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CurrentTimeUT", action = "http://webservices.cloanto.com/currencyserver/CurrentTimeUT")
    @WebResult(name = "CurrentTimeUTResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "CurrentTimeUT", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrentTimeUT")
    @ResponseWrapper(localName = "CurrentTimeUTResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.CurrentTimeUTResponse")
    public String currentTimeUT(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns a currency code (ISO 4217 Alpha-3) associated to the specified domain (string ending with IANA TLD).
     * 
     * @param activeOnly
     * @param licenseKey
     * @param domain
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DomainToCurrency", action = "http://webservices.cloanto.com/currencyserver/DomainToCurrency")
    @WebResult(name = "DomainToCurrencyResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "DomainToCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.DomainToCurrency")
    @ResponseWrapper(localName = "DomainToCurrencyResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.DomainToCurrencyResponse")
    public String domainToCurrency(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "domain", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String domain,
        @WebParam(name = "activeOnly", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        boolean activeOnly);

    /**
     * Returns the copyright information provided by the data source(s), if any.
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InformationCopyright", action = "http://webservices.cloanto.com/currencyserver/InformationCopyright")
    @WebResult(name = "InformationCopyrightResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "InformationCopyright", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationCopyright")
    @ResponseWrapper(localName = "InformationCopyrightResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationCopyrightResponse")
    public String informationCopyright(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the creation date and time of the current exchange rate data (local time). If this information is not available an empty string is returned.
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InformationCreationTimeLocal", action = "http://webservices.cloanto.com/currencyserver/InformationCreationTimeLocal")
    @WebResult(name = "InformationCreationTimeLocalResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "InformationCreationTimeLocal", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationCreationTimeLocal")
    @ResponseWrapper(localName = "InformationCreationTimeLocalResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationCreationTimeLocalResponse")
    public String informationCreationTimeLocal(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the creation date and time of the current exchange rate data (Universal Time). If this information is not available an empty string is returned.
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InformationCreationTimeUT", action = "http://webservices.cloanto.com/currencyserver/InformationCreationTimeUT")
    @WebResult(name = "InformationCreationTimeUTResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "InformationCreationTimeUT", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationCreationTimeUT")
    @ResponseWrapper(localName = "InformationCreationTimeUTResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationCreationTimeUTResponse")
    public String informationCreationTimeUT(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the expiration date and time of the current exchange rate data (local time). If this information is not available an empty string is returned.
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InformationExpirationTimeLocal", action = "http://webservices.cloanto.com/currencyserver/InformationExpirationTimeLocal")
    @WebResult(name = "InformationExpirationTimeLocalResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "InformationExpirationTimeLocal", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationExpirationTimeLocal")
    @ResponseWrapper(localName = "InformationExpirationTimeLocalResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationExpirationTimeLocalResponse")
    public String informationExpirationTimeLocal(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the expiration date and time of the current exchange rate data (Universal Time). If this information is not available an empty string is returned.
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InformationExpirationTimeUT", action = "http://webservices.cloanto.com/currencyserver/InformationExpirationTimeUT")
    @WebResult(name = "InformationExpirationTimeUTResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "InformationExpirationTimeUT", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationExpirationTimeUT")
    @ResponseWrapper(localName = "InformationExpirationTimeUTResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationExpirationTimeUTResponse")
    public String informationExpirationTimeUT(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the message(s) from the data source(s), if any.
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InformationMessage", action = "http://webservices.cloanto.com/currencyserver/InformationMessage")
    @WebResult(name = "InformationMessageResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "InformationMessage", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationMessage")
    @ResponseWrapper(localName = "InformationMessageResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationMessageResponse")
    public String informationMessage(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the name(s) of the data source(s).
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InformationSource", action = "http://webservices.cloanto.com/currencyserver/InformationSource")
    @WebResult(name = "InformationSourceResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "InformationSource", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationSource")
    @ResponseWrapper(localName = "InformationSourceResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.InformationSourceResponse")
    public String informationSource(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the date and time of the last modification to the current exchange rate data (local time). If the rates have never been set or changed an empty string is returned.
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LastChangeTimeLocal", action = "http://webservices.cloanto.com/currencyserver/LastChangeTimeLocal")
    @WebResult(name = "LastChangeTimeLocalResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "LastChangeTimeLocal", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.LastChangeTimeLocal")
    @ResponseWrapper(localName = "LastChangeTimeLocalResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.LastChangeTimeLocalResponse")
    public String lastChangeTimeLocal(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the date and time of the last modification to the current exchange rate data (Universal Time). If the rates have never been set or changed an empty string is returned.
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LastChangeTimeUT", action = "http://webservices.cloanto.com/currencyserver/LastChangeTimeUT")
    @WebResult(name = "LastChangeTimeUTResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "LastChangeTimeUT", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.LastChangeTimeUT")
    @ResponseWrapper(localName = "LastChangeTimeUTResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.LastChangeTimeUTResponse")
    public String lastChangeTimeUT(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns a currency code (ISO 4217 Alpha-3) associated to the specified locale (Windows LCID or ISO 639-2 Alpha-2).
     * 
     * @param activeOnly
     * @param licenseKey
     * @param locale
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "LocaleToCurrency", action = "http://webservices.cloanto.com/currencyserver/LocaleToCurrency")
    @WebResult(name = "LocaleToCurrencyResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "LocaleToCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.LocaleToCurrency")
    @ResponseWrapper(localName = "LocaleToCurrencyResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.LocaleToCurrencyResponse")
    public String localeToCurrency(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "locale", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String locale,
        @WebParam(name = "activeOnly", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        boolean activeOnly);

    /**
     * Returns the exchange (conversion) rate. The result is a number which can optionally be rounded. Leave the date and type parameters empty for forward compatibility.
     * 
     * @param date
     * @param licenseKey
     * @param toCurrency
     * @param rounding
     * @param type
     * @param baseCurrency
     * @return
     *     returns double
     */
    @WebMethod(operationName = "RateNum", action = "http://webservices.cloanto.com/currencyserver/RateNum")
    @WebResult(name = "RateNumResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "RateNum", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.RateNum")
    @ResponseWrapper(localName = "RateNumResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.RateNumResponse")
    public double rateNum(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "baseCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String baseCurrency,
        @WebParam(name = "toCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String toCurrency,
        @WebParam(name = "rounding", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        boolean rounding,
        @WebParam(name = "date", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String date,
        @WebParam(name = "type", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String type);

    /**
     * Returns the exchange (conversion) rate. The result is a string which can optionally be rounded and formatted. Either baseCurrency or toCurrency (but not both) may contain a list of semicolon-separated active currencies. Leave the date and type parameters empty for forward compatibility.
     * 
     * @param date
     * @param licenseKey
     * @param toCurrency
     * @param format
     * @param rounding
     * @param type
     * @param baseCurrency
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RateStr", action = "http://webservices.cloanto.com/currencyserver/RateStr")
    @WebResult(name = "RateStrResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "RateStr", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.RateStr")
    @ResponseWrapper(localName = "RateStrResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.RateStrResponse")
    public String rateStr(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "baseCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String baseCurrency,
        @WebParam(name = "toCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String toCurrency,
        @WebParam(name = "rounding", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        boolean rounding,
        @WebParam(name = "format", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String format,
        @WebParam(name = "date", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String date,
        @WebParam(name = "type", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String type);

    /**
     * Returns the effective date and time (local time) of the exchange or conversion rate of toCurrency, relative to baseCurrency. Leave the date and type parameters empty for forward compatibility.
     * 
     * @param date
     * @param licenseKey
     * @param toCurrency
     * @param priority
     * @param type
     * @param baseCurrency
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RateTimeLocal", action = "http://webservices.cloanto.com/currencyserver/RateTimeLocal")
    @WebResult(name = "RateTimeLocalResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "RateTimeLocal", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.RateTimeLocal")
    @ResponseWrapper(localName = "RateTimeLocalResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.RateTimeLocalResponse")
    public String rateTimeLocal(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "baseCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String baseCurrency,
        @WebParam(name = "toCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String toCurrency,
        @WebParam(name = "priority", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String priority,
        @WebParam(name = "date", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String date,
        @WebParam(name = "type", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String type);

    /**
     * Returns the effective date and time (Universal Time) of the exchange or conversion rate of toCurrency, relative to baseCurrency. Leave the date and type parameters empty for forward compatibility.
     * 
     * @param date
     * @param licenseKey
     * @param toCurrency
     * @param priority
     * @param type
     * @param baseCurrency
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RateTimeUT", action = "http://webservices.cloanto.com/currencyserver/RateTimeUT")
    @WebResult(name = "RateTimeUTResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "RateTimeUT", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.RateTimeUT")
    @ResponseWrapper(localName = "RateTimeUTResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.RateTimeUTResponse")
    public String rateTimeUT(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey,
        @WebParam(name = "baseCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String baseCurrency,
        @WebParam(name = "toCurrency", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String toCurrency,
        @WebParam(name = "priority", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String priority,
        @WebParam(name = "date", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String date,
        @WebParam(name = "type", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String type);

    /**
     * Returns the seconds elapsed since the last modification to one or more exchange rates.
     * 
     * @param licenseKey
     * @return
     *     returns long
     */
    @WebMethod(operationName = "SecondsSinceLastChange", action = "http://webservices.cloanto.com/currencyserver/SecondsSinceLastChange")
    @WebResult(name = "SecondsSinceLastChangeResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "SecondsSinceLastChange", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.SecondsSinceLastChange")
    @ResponseWrapper(localName = "SecondsSinceLastChangeResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.SecondsSinceLastChangeResponse")
    public long secondsSinceLastChange(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

    /**
     * Returns the software version.
     * 
     * @param licenseKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Version", action = "http://webservices.cloanto.com/currencyserver/Version")
    @WebResult(name = "VersionResult", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
    @RequestWrapper(localName = "Version", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.Version")
    @ResponseWrapper(localName = "VersionResponse", targetNamespace = "http://webservices.cloanto.com/currencyserver/", className = "com.cloanto.webservices.currencyserver.VersionResponse")
    public String version(
        @WebParam(name = "licenseKey", targetNamespace = "http://webservices.cloanto.com/currencyserver/")
        String licenseKey);

}
